driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd

suites:
  #
  # config
  #
  - name: config
    run_list:
    - recipe[httpd_config_test]

  #
  # modules
  #
  - name: module22
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-6'
      ]
    attributes:
      httpd:
        version: '2.2'

  - name: module24
    run_list:
    - recipe[httpd_module_test]
    includes: [
      'centos-7',
      'debian-8',
      'debian-9',
      'fedora-latest',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'opensuse-leap'
      ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service22-single
  #
  - name: service22-single
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-6'
      ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service22-multi
  #
  - name: service22-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-6'
      ]
    attributes:
      httpd:
        contact: 'bob@computers.biz'
        version: '2.2'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        run_user: 'bob'
        run_group: 'bob'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        maxspareservers: '40'
        log_level: 'warn'
        maxkeepaliverequests: '2001'

  #
  # service22-actions
  #
  - name: service22-actions
    run_list:
    - recipe[httpd_service_test::actions]
    includes: [
      'centos-6'
      ]
    attributes:
      httpd:
        version: '2.2'

  #
  # service24-single
  #
  - name: service24-single
    driver:
    run_list:
    - recipe[httpd_service_test::single]
    includes: [
      'centos-7',
      'fedora-latest',
      'debian-8',
      'debian-9',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'opensuse-leap'
      ]
    attributes:
      httpd:
        version: '2.4'

  #
  # service24-multi-docker
  #
  - name: service24-multi
    run_list:
    - recipe[httpd_service_test::multi]
    includes: [
      'centos-7',
      'debian-8',
      'debian-9',
      'fedora-latest',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'opensuse-leap'
      ]
    attributes:
      httpd:
        version: '2.4'
        service_name: 'multi'
        listen_ports: [ '81', '444' ]
        log_level: 'warn'
        run_user: 'bob'
        run_group: 'bob'
        contact: 'alice@computers.biz'
        timeout: '1234'
        keepalive: false
        keepaliverequests: '5678'
        keepalivetimeout: '8765'
        mpm: 'prefork'
        startservers: '20'
        minspareservers: '20'
        maxspareservers: '40'
        maxkeepaliverequests: '2001'

  #
  # service24-actions
  #
  - name: service24-actions
    driver:
    run_list:
    - recipe[httpd_service_test::actions]
    includes: [
      'centos-7',
      'debian-8',
      'debian-9',
      'fedora-latest',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'opensuse-leap'
      ]
    attributes:
      httpd:
        version: '2.4'
